import { defineConfig } from 'vitest/config';

export default defineConfig({
	test: {
		name: 'unit',
		environment: 'node',
		include: [
			'test/rollup-math.spec.ts',
			'test/combine-metrics.spec.ts',
			'test/ranking.spec.ts',
			'test/dates.spec.ts',
			'test/rollup-daily-job.spec.ts',
			'test/cron-messages.spec.ts',
			'test/messages.spec.ts',
			'test/scheduled-cron.spec.ts',
			'test/ingest-budget.spec.ts',
			'test/helix-to-rollup.integration.spec.ts',
			'test/admin-auth.spec.ts',
			'test/public-http-edge.spec.ts',
			'test/follower-snapshots.spec.ts',
			'test/prune-samples.spec.ts',
			'test/search-channels.spec.ts',
			'test/search-db.spec.ts',
			'test/health-status.spec.ts',
			'test/health-public.spec.ts',
			'test/twitch-credentials.spec.ts',
			'test/top-channels.spec.ts',
			'test/ranking-period.spec.ts',
			'test/channels-api.spec.ts',
			'test/channel-api.spec.ts',
			'test/live-sightings.spec.ts',
			'test/reconcile-retire.spec.ts',
			'test/eventsub-lifecycle.spec.ts',
			'test/games-api.spec.ts',
			'test/game-api.spec.ts',
			'test/top-games.spec.ts',
			'test/enrich-before-rollup.spec.ts',
			'test/wrangler-production-env.spec.ts',
			'test/wrangler-staging-env.spec.ts',
			'test/wrangler-bindings.spec.ts',
			'test/sample-archive.spec.ts',
			'test/channel-state.spec.ts',
			'test/health-metrics.spec.ts',
			'test/seed-rankings.spec.ts',
			'test/dev-admin-guard.spec.ts',
			'test/ranking-min-airtime-env.spec.ts',
			'test/ingest-counts.spec.ts',
			'test/discovery-seed.spec.ts',
			'test/helix-stream-persist.spec.ts',
			'test/helix-profile-enrichment.spec.ts',
			'test/helix-users-channels.spec.ts',
			'test/platform-id.spec.ts',
			'test/slug-collision.spec.ts',
			'test/channel-sighting-order.spec.ts',
			'test/ingest-stream-order.spec.ts',
			'test/helix-streams-pagination.spec.ts',
			'test/helix-pagination.spec.ts',
			'test/sweep-game-pass.spec.ts',
			'test/stream-page.spec.ts',
			'test/auth.spec.ts',
			'test/config-env.spec.ts',
			'test/twitch-sweep-discover.spec.ts',
			'test/game-pass.spec.ts',
			'test/twitch-poll.spec.ts',
			'test/poll-platform.spec.ts',
			'test/coverage-fanout.spec.ts',
			'test/helix-budget.spec.ts',
			'test/helix-rate-limit-retry.spec.ts',
			'test/top-games-cache.spec.ts',
			'test/poll-batch-offline.spec.ts',
			'test/session-lifecycle.spec.ts',
			'test/twitch-live-batch.spec.ts',
			'test/twitch-config-env.spec.ts',
			'test/coverage-cycle.spec.ts',
			'test/eventsub-timestamp.spec.ts',
			'test/channel-api-edge.spec.ts',
			'test/channel-resolve.spec.ts',
			'test/game-api-edge.spec.ts',
			'test/rate-limit.spec.ts',
			'test/rankings-cache.spec.ts',
			'test/helix-followers.spec.ts',
			'test/db-twitch-lists.spec.ts',
			'test/db-kick-lists.spec.ts',
			'test/kick-auth.spec.ts',
			'test/kick-api.spec.ts',
			'test/kick-poll.spec.ts',
			'test/kick-discover.spec.ts',
			'test/kick-discover-edge.spec.ts',
			'test/kick-api-edge.spec.ts',
			'test/kick-webhook-verify.spec.ts',
			'test/kick-webhook-timestamp.spec.ts',
			'test/kick-webhook-handler.spec.ts',
			'test/kick-webhook-lifecycle.spec.ts',
			'test/kick-admin-routes.spec.ts',
			'test/kick-stream-fields.spec.ts',
			'test/db-youtube-lists.spec.ts',
			'test/youtube-api.spec.ts',
			'test/youtube-poll.spec.ts',
			'test/eventsub-subscriptions.spec.ts',
			'test/eventsub-sync-cursor.spec.ts',
			'test/eventsub-message-dedup.spec.ts',
			'test/eventsub-secret.spec.ts',
			'test/eventsub-handler.spec.ts',
			'test/eventsub-verify.spec.ts',
			'test/db-channel-slug.spec.ts'
		],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'html'],
			include: ['src/twitch/**/*.ts', 'src/db/**/*.ts', 'src/kick/**/*.ts'],
			exclude: ['src/twitch/**/index.ts'],
			thresholds: {
				'src/twitch/**': {
					lines: 80,
					functions: 80,
					branches: 80,
					statements: 80
				},
				'src/db/**': {
					lines: 80,
					functions: 80,
					branches: 80,
					statements: 80
				},
				'src/kick/**': {
					lines: 80,
					functions: 80,
					branches: 80,
					statements: 80
				}
			}
		}
	}
});
